### ISSUE TITLE
error when enable on 2.79.6

### ISSUE THREAD

**Issue by brothermechanic** [dairin0d/batch-operations#5]
```
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/2.79/scripts/addons/space_view3d_batch_operations/__init__.py", line 58, in <module>
    from . import batch_common
  File "/usr/share/blender/2.79/scripts/addons/space_view3d_batch_operations/batch_common.py", line 376, in <module>
    @addon.Operator(idname="object.batch_streamline_meshes", options={'REGISTER', 'UNDO'}, label="Streamline mesh(es)", description="Streamline mesh(es)", mode={'OBJECT', 'EDIT_MESH'})
  File "/usr/share/blender/2.79/scripts/addons/space_view3d_batch_operations/batch_common.py", line 397, in Operator_batch_streamline_meshes
    symmetry_snap_direction = BlRna.to_bpy_prop(bpy.ops.mesh.symmetry_snap, "direction")
  File "/usr/share/blender/2.79/scripts/addons/space_view3d_batch_operations/dairin0d/bpy_inspect.py", line 300, in to_bpy_prop
    rna_prop = (obj if name is None else BlRna(obj).properties[name])
AttributeError: 'NoneType' object has no attribute 'properties'

```

**Comment by dairin0d** [comment]
Where did you download your 2.79.6 build? I tried to test this in the first one I could find (http://graphicall.org/1240 - Mantaflow Branch - 14/08/2018), but this problem doesn't occur there.

**Comment by brothermechanic** [comment]
This is my own (gentoo ebuild on python-3.6) )))

**Comment by brothermechanic** [comment]
ok, i test this one on buildbot's blender-2.79.6 (python3.7*) - same issue

**Comment by dairin0d** [comment]
Thanks! Please check the latest release (I uploaded it a minute ago), it should be fixed now.

**Comment by brothermechanic** [comment]
You Are My Hero!
Thank you!

**Comment by dairin0d** [comment]
Wow, I guess my addons must be pretty important to your workflow)) x-D
